
services:
  mc-server:
    build: .
    platform: linux/amd64
    ports:
      - "${PORT_OUT}:${APPLICATION_PORT}"
    environment:
      APPLICATION_PORT: ${APPLICATION_PORT}
    volumes:
      - local_data:/app/world
    restart: always

volumes:
  local_data:
