
services:
  mc-server:
    build: .
    platform: linux/amd64
    ports:
      - "${PORT_OUT}:${APLICATION_PORT}"
    environment:
      APLICATION_PORT: ${APLICATION_PORT}
    volumes:
      - local_data:/app/world
    restart: always

volumes:
  local_data:
