version: "3.8"

services:
  mc-server:
    container_name: minecraft-server
    build: .
    ports:
      - "${PORT_OUT}:${APLICATION_PORT}"
    environment:
      APLICATION_PORT: ${APLICATION_PORT}
    volumes:
      - ./data:/app/world
    restart: always
