
services:
  mc-server:
    build: .
    platform: linux/amd64
    ports:
      - "8888:25565"
    volumes:
      - local_data:/data
    restart: always
    env_file:
      - .env

volumes:
  local_data:
